const realmSeeds = [
    {
        "serverName": "Amnennar",
        "serverName": "Angerforge",
        "serverName": "Arugal",
        "serverName": "Ashbringer",
        "serverName": "Ashkandi",
        "serverName": "Atiesh",
        "serverName": "Auberdine",
        "serverName": "Azuresong",
        "serverName": "Benediction",
        "serverName": "Bloodsail Buccaneers",
        "serverName": "Earthfury",
        "serverName": "Earthshaker",
        "serverName": "Eranikus",
        "serverName": "Everlook",
        "serverName": "Faerlina",
        "serverName": "Firemaw",
        "serverName": "Gehennas",
        "serverName": "Giantstalker",
        "serverName": "Golemagg",
        "serverName": "Grobbulus",
        "serverName": "Hydraxian Waterlords",
        "serverName": "Jin’do",
        "serverName": "Lakeshire",
        "serverName": "Maladath",
        "serverName": "Mandokir",
        "serverName": "Mankrik",
        "serverName": "Mirage Raceway",
        "serverName": "Mograine",
        "serverName": "Nethergarde Keep",
        "serverName": "Old Blanchy",
        "serverName": "Pagle",
        "serverName": "Patchwerk",
        "serverName": "Pyrewood Village",
        "serverName": "Razorfen",
        "serverName": "Remulos",
        "serverName": "Skyfury",
        "serverName": "Sulfuras",
        "serverName": "Sulfuron",
        "serverName": "Thekal",
        "serverName": "Transcendence",
        "serverName": "Venoxis",
        "serverName": "Westfall",
        "serverName": "Whitemane",
        "serverName": "Windseeker",
        "serverName": "Yojamba",
        "serverName": "Пламегор",
        "serverName": "Хроми"
    }
]

module.exports = realmSeeds